name: Security
on: [push]
jobs:
  tartufo-scan:
    name: Tartufo
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0

      - uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: "3.x"

      - name: Install Tartufo
        run: pip3 install 'tartufo== ${{ secrets.OVER_SERVICES_TARTUFO_VERSION }}'

      - name: Log installed Tartufo version
        run: tartufo --version | sed s'/\./-/g'

      - name: Run Tartufo scan on current branch
        run: tartufo scan-local-repo --branch $(git branch --show-current) .
